// ui/src/AdminApp.tsx
import { useState } from 'preact/hooks'
import type { AdminPage, UserPool, User, UserPoolClient } from './lib/types'
import { Dashboard } from './admin/Dashboard'
import { UserPoolList } from './admin/UserPoolList'
import { UserPoolDetail } from './admin/UserPoolDetail'
import { UserList } from './admin/UserList'
import { UserDetail } from './admin/UserDetail'
import { ClientList } from './admin/ClientList'
import { ClientDetail } from './admin/ClientDetail'
import { BrandingEditor } from './admin/BrandingEditor'

export function AdminApp() {
  const [page, setPage] = useState<AdminPage>('dashboard')
  const [selectedUserPool, setSelectedUserPool] = useState<UserPool | null>(null)
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  const [selectedClient, setSelectedClient] = useState<UserPoolClient | null>(null)

  function navigate(newPage: AdminPage, context?: { userPool?: UserPool; user?: User; client?: UserPoolClient }) {
    setPage(newPage)
    if (context?.userPool !== undefined) setSelectedUserPool(context.userPool)
    if (context?.user !== undefined) setSelectedUser(context.user)
    if (context?.client !== undefined) setSelectedClient(context.client)
  }

  const navItems: { page: AdminPage; label: string; match: AdminPage[] }[] = [
    { page: 'dashboard', label: 'Dashboard', match: ['dashboard'] },
    { page: 'user-pools', label: 'User Pools', match: ['user-pools', 'user-pool-detail'] },
  ]

  const subNavItems: { page: AdminPage; label: string; match: AdminPage[] }[] = [
    { page: 'users', label: 'Users', match: ['users', 'user-detail'] },
    { page: 'clients', label: 'App Clients', match: ['clients', 'client-detail'] },
    { page: 'branding', label: 'Branding', match: ['branding'] },
  ]

  function renderContent() {
    switch (page) {
      case 'dashboard':
        return <Dashboard navigate={navigate} />
      case 'user-pools':
        return <UserPoolList navigate={navigate} />
      case 'user-pool-detail':
        return selectedUserPool ? <UserPoolDetail userPool={selectedUserPool} navigate={navigate} /> : null
      case 'users':
        return selectedUserPool ? <UserList userPool={selectedUserPool} navigate={navigate} /> : null
      case 'user-detail':
        return selectedUserPool && selectedUser ? <UserDetail userPool={selectedUserPool} user={selectedUser} navigate={navigate} /> : null
      case 'clients':
        return selectedUserPool ? <ClientList userPool={selectedUserPool} navigate={navigate} /> : null
      case 'client-detail':
        return selectedUserPool && selectedClient ? <ClientDetail userPool={selectedUserPool} client={selectedClient} navigate={navigate} /> : null
      case 'branding':
        return selectedUserPool ? <BrandingEditor userPool={selectedUserPool} navigate={navigate} /> : null
      default:
        return <div class="flex items-center justify-center h-96 text-base-content/50">Select an item from the sidebar to get started.</div>
    }
  }

  return (
    <div class="flex min-h-screen">
      <aside class="w-64 bg-base-300 text-base-content flex flex-col fixed h-screen overflow-y-auto">
        <div class="p-6 border-b border-base-content/10">
          <h1 class="text-2xl font-bold text-primary">Cognitox</h1>
          <span class="text-xs text-base-content/60">Admin Console</span>
        </div>

        <nav class="flex-1 py-4">
          <ul class="menu menu-sm w-full">
            {navItems.map(item => (
              <li key={item.page}>
                <button
                  class={item.match.includes(page) ? 'active' : ''}
                  onClick={() => navigate(item.page)}
                >
                  {item.label}
                </button>
              </li>
            ))}
            {selectedUserPool && (
              <li>
                <details open>
                  <summary class="text-base-content/60 text-xs uppercase tracking-wider">{selectedUserPool.Name}</summary>
                  <ul>
                    {subNavItems.map(item => (
                      <li key={item.page}>
                        <button
                          class={item.match.includes(page) ? 'active' : ''}
                          onClick={() => navigate(item.page)}
                        >
                          {item.label}
                        </button>
                      </li>
                    ))}
                  </ul>
                </details>
              </li>
            )}
          </ul>
        </nav>

        <div class="p-4 border-t border-base-content/10">
          <a href="/ui/" class="btn btn-ghost btn-sm w-full">Hosted UI</a>
        </div>
      </aside>

      <main class="flex-1 ml-64 p-6 min-h-screen bg-base-200">
        {renderContent()}
      </main>
    </div>
  )
}

// ui/src/AdminApp.svelte
<script lang="ts">
  import type { AdminPage, UserPool, User, UserPoolClient } from './lib/types'
  import Dashboard from './admin/Dashboard.svelte'
  import UserPoolList from './admin/UserPoolList.svelte'
  import UserPoolDetail from './admin/UserPoolDetail.svelte'
  import UserList from './admin/UserList.svelte'
  import UserDetail from './admin/UserDetail.svelte'
  import ClientList from './admin/ClientList.svelte'
  import ClientDetail from './admin/ClientDetail.svelte'
  import BrandingEditor from './admin/BrandingEditor.svelte'

  let page: AdminPage = $state('dashboard')
  let selectedUserPool: UserPool | null = $state(null)
  let selectedUser: User | null = $state(null)
  let selectedClient: UserPoolClient | null = $state(null)

  function navigate(newPage: AdminPage, context?: { userPool?: UserPool; user?: User; client?: UserPoolClient }) {
    page = newPage
    if (context?.userPool !== undefined) selectedUserPool = context.userPool
    if (context?.user !== undefined) selectedUser = context.user
    if (context?.client !== undefined) selectedClient = context.client
  }
</script>

<div class="admin-layout">
  <aside class="sidebar">
    <div class="logo">
      <h1>Cognitox</h1>
      <span class="subtitle">Admin Console</span>
    </div>

    <nav>
      <button
        class="nav-item"
        class:active={page === 'dashboard'}
        onclick={() => navigate('dashboard')}
      >
        Dashboard
      </button>
      <button
        class="nav-item"
        class:active={page === 'user-pools' || page === 'user-pool-detail'}
        onclick={() => navigate('user-pools')}
      >
        User Pools
      </button>
      {#if selectedUserPool}
        <div class="nav-sub">
          <button
            class="nav-item sub"
            class:active={page === 'users' || page === 'user-detail'}
            onclick={() => navigate('users')}
          >
            Users
          </button>
          <button
            class="nav-item sub"
            class:active={page === 'clients' || page === 'client-detail'}
            onclick={() => navigate('clients')}
          >
            App Clients
          </button>
          <button
            class="nav-item sub"
            class:active={page === 'branding'}
            onclick={() => navigate('branding')}
          >
            Branding
          </button>
        </div>
      {/if}
    </nav>

    <div class="sidebar-footer">
      <a href="/ui/" class="nav-item">Hosted UI</a>
    </div>
  </aside>

  <main class="content">
    {#if page === 'dashboard'}
      <Dashboard {navigate} />
    {:else if page === 'user-pools'}
      <UserPoolList {navigate} />
    {:else if page === 'user-pool-detail' && selectedUserPool}
      <UserPoolDetail userPool={selectedUserPool} {navigate} />
    {:else if page === 'users' && selectedUserPool}
      <UserList userPool={selectedUserPool} {navigate} />
    {:else if page === 'user-detail' && selectedUserPool && selectedUser}
      <UserDetail userPool={selectedUserPool} user={selectedUser} {navigate} />
    {:else if page === 'clients' && selectedUserPool}
      <ClientList userPool={selectedUserPool} {navigate} />
    {:else if page === 'client-detail' && selectedUserPool && selectedClient}
      <ClientDetail userPool={selectedUserPool} client={selectedClient} {navigate} />
    {:else if page === 'branding' && selectedUserPool}
      <BrandingEditor userPool={selectedUserPool} {navigate} />
    {:else}
      <div class="empty-state">
        <p>Select an item from the sidebar to get started.</p>
      </div>
    {/if}
  </main>
</div>

<style>
  .admin-layout {
    display: flex;
    min-height: 100vh;
    background-color: #f8f9fa;
  }

  .sidebar {
    width: 250px;
    background-color: #1a1a2e;
    color: white;
    display: flex;
    flex-direction: column;
    position: fixed;
    height: 100vh;
    overflow-y: auto;
  }

  .logo {
    padding: 24px 20px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  }

  .logo h1 {
    font-size: 24px;
    font-weight: 700;
    margin: 0;
    color: #4fc3f7;
  }

  .logo .subtitle {
    font-size: 12px;
    color: rgba(255, 255, 255, 0.6);
  }

  nav {
    flex: 1;
    padding: 16px 0;
  }

  .nav-item {
    display: block;
    width: 100%;
    padding: 12px 20px;
    border: none;
    background: none;
    color: rgba(255, 255, 255, 0.8);
    text-align: left;
    font-size: 14px;
    cursor: pointer;
    transition: all 0.2s;
    text-decoration: none;
  }

  .nav-item:hover {
    background-color: rgba(255, 255, 255, 0.1);
    color: white;
  }

  .nav-item.active {
    background-color: rgba(79, 195, 247, 0.2);
    color: #4fc3f7;
    border-left: 3px solid #4fc3f7;
  }

  .nav-sub {
    background-color: rgba(0, 0, 0, 0.2);
  }

  .nav-item.sub {
    padding-left: 36px;
    font-size: 13px;
  }

  .sidebar-footer {
    padding: 16px 0;
    border-top: 1px solid rgba(255, 255, 255, 0.1);
  }

  .content {
    flex: 1;
    margin-left: 250px;
    padding: 24px;
    min-height: 100vh;
  }

  .empty-state {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 400px;
    color: #666;
  }
</style>
