// ui/src/App.tsx
import { useState, useEffect } from 'preact/hooks'
import type { Page, OAuthParams, Branding } from './lib/types'
import { getBranding } from './lib/api'
import { Login } from './routes/Login'
import { Signup } from './routes/Signup'
import { Confirm } from './routes/Confirm'
import { ForgotPassword } from './routes/ForgotPassword'
import { ResetPassword } from './routes/ResetPassword'

export function App() {
  const [page, setPage] = useState<Page>('login')
  const [oauth, setOauth] = useState<OAuthParams>({
    response_type: 'code',
    client_id: '',
    redirect_uri: '',
    scope: 'openid',
  })
  const [branding, setBranding] = useState<Branding>({
    pageTitle: 'Sign In',
    signInHeader: 'Welcome',
    signInSubheader: 'Sign in to continue',
    backgroundColor: '#f5f5f5',
    primaryColor: '#007bff',
    textColor: '#333333',
    buttonColor: '#007bff',
    buttonTextColor: '#ffffff',
  })
  const [username, setUsername] = useState('')
  const [error, setErrorState] = useState<string | undefined>(undefined)
  const [success, setSuccessState] = useState<string | undefined>(undefined)
  const [loading, setLoading] = useState(true)

  function setError(msg: string) {
    setErrorState(msg)
    setSuccessState(undefined)
  }

  function setSuccess(msg: string) {
    setSuccessState(msg)
    setErrorState(undefined)
  }

  function getBasePath(pathname: string): string {
    if (pathname === '/ui' || pathname.startsWith('/ui/')) {
      return '/ui'
    }

    return ''
  }

  function getPageFromPath(pathname: string): Page {
    if (pathname.endsWith('/signup')) return 'signup'
    if (pathname.endsWith('/confirm')) return 'confirm'
    if (pathname.endsWith('/forgot-password')) return 'forgot-password'
    if (pathname.endsWith('/reset-password')) return 'reset-password'
    return 'login'
  }

  function buildSearchParams(params?: { username?: string }): URLSearchParams {
    const searchParams = new URLSearchParams()
    searchParams.set('response_type', oauth.response_type)
    searchParams.set('client_id', oauth.client_id)
    searchParams.set('redirect_uri', oauth.redirect_uri)
    searchParams.set('scope', oauth.scope || 'openid')
    if (oauth.state) searchParams.set('state', oauth.state)
    if (oauth.nonce) searchParams.set('nonce', oauth.nonce)
    if (oauth.code_challenge) searchParams.set('code_challenge', oauth.code_challenge)
    if (oauth.code_challenge_method) searchParams.set('code_challenge_method', oauth.code_challenge_method)
    if (params?.username) {
      searchParams.set('username', params.username)
    } else if (username) {
      searchParams.set('username', username)
    }

    return searchParams
  }

  function getPagePath(pageName: Page): string {
    const suffix = pageName === 'login' ? '' : `/${pageName}`
    const basePath = getBasePath(window.location.pathname)
    return `${basePath}${suffix || '/'}`
  }

  function syncFromLocation(): OAuthParams {
    const params = new URLSearchParams(window.location.search)
    const oauthParams: OAuthParams = {
      response_type: params.get('response_type') || 'code',
      client_id: params.get('client_id') || '',
      redirect_uri: params.get('redirect_uri') || '',
      scope: params.get('scope') || 'openid',
      state: params.get('state') || undefined,
      nonce: params.get('nonce') || undefined,
      code_challenge: params.get('code_challenge') || undefined,
      code_challenge_method: params.get('code_challenge_method') || undefined,
    }

    setOauth(oauthParams)
    setUsername(params.get('username') || '')
    setPage(getPageFromPath(window.location.pathname))

    return oauthParams
  }

  function navigate(newPage: Page, params?: { username?: string }) {
    setPage(newPage)
    if (params?.username) setUsername(params.username)
    setErrorState(undefined)
    setSuccessState(undefined)

    const searchParams = buildSearchParams(params)
    const nextUrl = `${getPagePath(newPage)}?${searchParams.toString()}`
    window.history.pushState({ page: newPage }, '', nextUrl)
  }

  useEffect(() => {
    const oauthParams = syncFromLocation()

    ;(async () => {
      if (oauthParams.client_id) {
        const b = await getBranding(oauthParams.client_id)
        setBranding(b)
        document.documentElement.style.setProperty('--primary-color', b.primaryColor)
        document.documentElement.style.setProperty('--background-color', b.backgroundColor)
        document.documentElement.style.setProperty('--text-color', b.textColor)
        document.documentElement.style.setProperty('--button-color', b.buttonColor)
        document.documentElement.style.setProperty('--button-text-color', b.buttonTextColor)
        document.title = b.pageTitle
      }
      setLoading(false)
    })()

    const handlePopState = () => {
      setErrorState(undefined)
      setSuccessState(undefined)
      syncFromLocation()
    }

    window.addEventListener('popstate', handlePopState)

    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [])

  if (loading) {
    return <div class="flex items-center justify-center min-h-screen"><span class="loading loading-spinner loading-lg"></span></div>
  }

  if (!oauth.client_id) {
    return (
      <div class="flex items-center justify-center min-h-screen p-5" style={{ backgroundColor: 'var(--background-color)' }}>
        <div class="card bg-base-100 shadow-lg">
          <div class="card-body text-center">
            <h1 class="text-xl font-bold text-error">Missing Parameters</h1>
            <p>client_id and redirect_uri are required.</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div class="flex items-center justify-center min-h-screen p-5" style={{ backgroundColor: 'var(--background-color)' }}>
      {page === 'login' && <Login oauth={oauth} branding={branding} error={error} navigate={navigate} setError={setError} />}
      {page === 'signup' && <Signup oauth={oauth} branding={branding} error={error} navigate={navigate} setError={setError} />}
      {page === 'confirm' && <Confirm oauth={oauth} branding={branding} username={username} error={error} success={success} navigate={navigate} setError={setError} setSuccess={setSuccess} />}
      {page === 'forgot-password' && <ForgotPassword oauth={oauth} branding={branding} error={error} navigate={navigate} />}
      {page === 'reset-password' && <ResetPassword oauth={oauth} branding={branding} username={username} error={error} navigate={navigate} setError={setError} />}
    </div>
  )
}

// ui/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { Page, OAuthParams, Branding } from './lib/types'
  import { getBranding } from './lib/api'
  import Login from './routes/Login.svelte'
  import Signup from './routes/Signup.svelte'
  import Confirm from './routes/Confirm.svelte'
  import ForgotPassword from './routes/ForgotPassword.svelte'
  import ResetPassword from './routes/ResetPassword.svelte'

  let page: Page = $state('login')
  let oauth: OAuthParams = $state({
    response_type: 'code',
    client_id: '',
    redirect_uri: '',
    scope: 'openid',
  })
  let branding: Branding = $state({
    pageTitle: 'Sign In',
    signInHeader: 'Welcome',
    signInSubheader: 'Sign in to continue',
    backgroundColor: '#f5f5f5',
    primaryColor: '#007bff',
    textColor: '#333333',
    buttonColor: '#007bff',
    buttonTextColor: '#ffffff',
  })
  let username: string = $state('')
  let error: string | undefined = $state(undefined)
  let success: string | undefined = $state(undefined)
  let loading: boolean = $state(true)

  function getBasePath(pathname: string): string {
    if (pathname === '/ui' || pathname.startsWith('/ui/')) {
      return '/ui'
    }

    return ''
  }

  function getPageFromPath(pathname: string): Page {
    if (pathname.endsWith('/signup')) {
      return 'signup'
    }

    if (pathname.endsWith('/confirm')) {
      return 'confirm'
    }

    if (pathname.endsWith('/forgot-password')) {
      return 'forgot-password'
    }

    if (pathname.endsWith('/reset-password')) {
      return 'reset-password'
    }

    return 'login'
  }

  function buildSearchParams(params?: { username?: string }): URLSearchParams {
    const searchParams = new URLSearchParams()
    searchParams.set('response_type', oauth.response_type)
    searchParams.set('client_id', oauth.client_id)
    searchParams.set('redirect_uri', oauth.redirect_uri)
    searchParams.set('scope', oauth.scope || 'openid')
    if (oauth.state) searchParams.set('state', oauth.state)
    if (oauth.nonce) searchParams.set('nonce', oauth.nonce)
    if (oauth.code_challenge) searchParams.set('code_challenge', oauth.code_challenge)
    if (oauth.code_challenge_method) searchParams.set('code_challenge_method', oauth.code_challenge_method)
    if (params?.username) {
      searchParams.set('username', params.username)
    } else if (username) {
      searchParams.set('username', username)
    }

    return searchParams
  }

  function getPagePath(pageName: Page): string {
    const suffix = pageName === 'login' ? '' : `/${pageName}`
    const basePath = getBasePath(window.location.pathname)

    return `${basePath}${suffix || '/'}`
  }

  function syncFromLocation(): void {
    const params = new URLSearchParams(window.location.search)

    oauth = {
      response_type: params.get('response_type') || 'code',
      client_id: params.get('client_id') || '',
      redirect_uri: params.get('redirect_uri') || '',
      scope: params.get('scope') || 'openid',
      state: params.get('state') || undefined,
      nonce: params.get('nonce') || undefined,
      code_challenge: params.get('code_challenge') || undefined,
      code_challenge_method: params.get('code_challenge_method') || undefined,
    }

    username = params.get('username') || ''
    page = getPageFromPath(window.location.pathname)
  }

  function navigate(newPage: Page, params?: { username?: string }) {
    page = newPage
    if (params?.username) {
      username = params.username
    }
    error = undefined
    success = undefined

    const searchParams = buildSearchParams(params)
    const nextUrl = `${getPagePath(newPage)}?${searchParams.toString()}`

    window.history.pushState({ page: newPage }, '', nextUrl)
  }

  onMount(async () => {
    syncFromLocation()

    if (oauth.client_id) {
      branding = await getBranding(oauth.client_id)
    }

    // Apply branding as CSS variables
    document.documentElement.style.setProperty('--primary-color', branding.primaryColor)
    document.documentElement.style.setProperty('--background-color', branding.backgroundColor)
    document.documentElement.style.setProperty('--text-color', branding.textColor)
    document.documentElement.style.setProperty('--button-color', branding.buttonColor)
    document.documentElement.style.setProperty('--button-text-color', branding.buttonTextColor)
    document.title = branding.pageTitle

    const handlePopState = () => {
      error = undefined
      success = undefined
      syncFromLocation()
    }

    window.addEventListener('popstate', handlePopState)
    loading = false

    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  })

  function setError(msg: string) {
    error = msg
    success = undefined
  }

  function setSuccess(msg: string) {
    success = msg
    error = undefined
  }
</script>

{#if loading}
  <div class="loading">Loading...</div>
{:else if !oauth.client_id}
  <div class="error-container">
    <h1>Missing Parameters</h1>
    <p>client_id and redirect_uri are required.</p>
  </div>
{:else}
  {#if page === 'login'}
    <Login {oauth} {branding} {error} {navigate} {setError} />
  {:else if page === 'signup'}
    <Signup {oauth} {branding} {error} {navigate} {setError} />
  {:else if page === 'confirm'}
    <Confirm {oauth} {branding} {username} {error} {success} {navigate} {setError} {setSuccess} />
  {:else if page === 'forgot-password'}
    <ForgotPassword {oauth} {branding} {error} {navigate} />
  {:else if page === 'reset-password'}
    <ResetPassword {oauth} {branding} {username} {error} {navigate} {setError} />
  {/if}
{/if}

<style>
  .loading {
    text-align: center;
    padding: 40px;
    font-size: 18px;
    color: #666;
  }

  .error-container {
    background: white;
    padding: 40px;
    border-radius: 8px;
    text-align: center;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  }

  .error-container h1 {
    color: var(--error-color);
    margin-bottom: 16px;
  }
</style>
