// ui/src/routes/Login.tsx
import { useState } from 'preact/hooks'
import type { OAuthParams, Branding, Page } from '../lib/types'
import { login } from '../lib/api'
import { Card } from '../lib/Card'

interface Props {
  oauth: OAuthParams
  branding: Branding
  error?: string
  navigate: (page: Page, params?: { username?: string }) => void
  setError: (msg: string) => void
}

export function Login({ oauth, branding, error, navigate, setError }: Props) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [submitting, setSubmitting] = useState(false)

  async function handleSubmit(e: Event) {
    e.preventDefault()
    setSubmitting(true)
    const result = await login(username, password, oauth)
    if (result.success && result.redirectUrl) {
      window.location.href = result.redirectUrl
    } else {
      setError(result.error || 'Login failed')
      setSubmitting(false)
    }
  }

  return (
    <Card branding={branding}>
      <h1 class="text-2xl font-semibold text-center mb-2">{branding.signInHeader}</h1>
      <p class="text-center text-sm text-base-content/60 mb-6">{branding.signInSubheader}</p>

      {error && <div class="alert alert-error text-sm mb-4">{error}</div>}

      <form onSubmit={handleSubmit}>
        <div class="form-control mb-4">
          <label class="label"><span class="label-text">Username</span></label>
          <input type="text" class="input input-bordered" value={username} onInput={e => setUsername((e.target as HTMLInputElement).value)} required disabled={submitting} autoComplete="username" />
        </div>
        <div class="form-control mb-4">
          <label class="label"><span class="label-text">Password</span></label>
          <input type="password" class="input input-bordered" value={password} onInput={e => setPassword((e.target as HTMLInputElement).value)} required disabled={submitting} autoComplete="current-password" />
        </div>
        <button type="submit" class="btn btn-primary w-full" disabled={submitting} style={{ backgroundColor: 'var(--button-color)', color: 'var(--button-text-color)' }}>
          {submitting ? <><span class="loading loading-spinner loading-sm"></span> Signing in...</> : 'Sign In'}
        </button>
      </form>

      <div class="text-center mt-6 space-y-3">
        <button class="link link-primary text-sm" onClick={() => navigate('forgot-password')}>Forgot password?</button>
        <div class="text-xs text-base-content/40">or</div>
        <button class="link link-primary text-sm" onClick={() => navigate('signup')}>Create an account</button>
      </div>
    </Card>
  )
}

// ui/src/routes/Login.svelte
<script lang="ts">
  import type { OAuthParams, Branding, Page } from '../lib/types'
  import { login } from '../lib/api'
  import Card from '../lib/Card.svelte'

  interface Props {
    oauth: OAuthParams
    branding: Branding
    error?: string
    navigate: (page: Page, params?: { username?: string }) => void
    setError: (msg: string) => void
  }

  let { oauth, branding, error, navigate, setError }: Props = $props()

  let username = $state('')
  let password = $state('')
  let submitting = $state(false)

  async function handleSubmit(e: Event) {
    e.preventDefault()
    submitting = true

    const result = await login(username, password, oauth)

    if (result.success && result.redirectUrl) {
      window.location.href = result.redirectUrl
    } else {
      setError(result.error || 'Login failed')
      submitting = false
    }
  }
</script>

<Card {branding}>
  <h1>{branding.signInHeader}</h1>
  <p class="subheader">{branding.signInSubheader}</p>

  {#if error}
    <div class="error">{error}</div>
  {/if}

  <form onsubmit={handleSubmit}>
    <div class="form-group">
      <label for="username">Username</label>
      <input
        type="text"
        id="username"
        bind:value={username}
        required
        disabled={submitting}
        autocomplete="username"
      />
    </div>

    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        id="password"
        bind:value={password}
        required
        disabled={submitting}
        autocomplete="current-password"
      />
    </div>

    <button type="submit" class="btn btn-primary" disabled={submitting}>
      {submitting ? 'Signing in...' : 'Sign In'}
    </button>
  </form>

  <div class="links">
    <button type="button" class="link-btn" onclick={() => navigate('forgot-password')}>
      Forgot password?
    </button>
    <span class="divider">or</span>
    <button type="button" class="link-btn" onclick={() => navigate('signup')}>
      Create an account
    </button>
  </div>
</Card>

<style>
  h1 {
    font-size: 24px;
    font-weight: 600;
    text-align: center;
    margin-bottom: 8px;
  }

  .subheader {
    text-align: center;
    color: #666;
    margin-bottom: 24px;
    font-size: 14px;
  }

  .error {
    background-color: #fee;
    border: 1px solid #fcc;
    color: #c00;
    padding: 12px;
    border-radius: 4px;
    margin-bottom: 16px;
    font-size: 14px;
  }

  .form-group {
    margin-bottom: 16px;
  }

  label {
    display: block;
    margin-bottom: 6px;
    font-size: 14px;
    font-weight: 500;
  }

  input {
    width: 100%;
    padding: 12px;
    border: 1px solid var(--border-color);
    border-radius: 4px;
    font-size: 16px;
    transition: border-color 0.2s;
  }

  input:focus {
    outline: none;
    border-color: var(--primary-color);
  }

  input:disabled {
    background-color: #f5f5f5;
    cursor: not-allowed;
  }

  .btn {
    width: 100%;
    padding: 12px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    font-weight: 500;
    cursor: pointer;
    transition: opacity 0.2s;
  }

  .btn:hover:not(:disabled) {
    opacity: 0.9;
  }

  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .btn-primary {
    background-color: var(--button-color, var(--primary-color));
    color: var(--button-text-color, white);
  }

  .links {
    margin-top: 24px;
    text-align: center;
  }

  .link-btn {
    background: none;
    border: none;
    color: var(--primary-color);
    cursor: pointer;
    font-size: 14px;
    text-decoration: underline;
  }

  .link-btn:hover {
    opacity: 0.8;
  }

  .divider {
    display: block;
    margin: 12px 0;
    color: #999;
    font-size: 12px;
  }
</style>
