// ui/src/lib/Card.svelte
<script lang="ts">
  import type { Branding } from './types'
  import type { Snippet } from 'svelte'

  interface Props {
    branding: Branding
    children: Snippet
  }

  let { branding, children }: Props = $props()
</script>

<div class="card">
  {#if branding.logoUrl}
    <div class="logo">
      <img src={branding.logoUrl} alt="Logo" />
    </div>
  {/if}
  {@render children()}
</div>

<style>
  .card {
    background: var(--card-background, white);
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    padding: 40px;
    width: 100%;
    max-width: 400px;
  }

  .logo {
    text-align: center;
    margin-bottom: 24px;
  }

  .logo img {
    max-width: 150px;
    max-height: 60px;
  }
</style>

// ui/src/lib/Card.tsx
import type { ComponentChildren } from 'preact'
import type { Branding } from './types'

interface Props {
  branding: Branding
  children: ComponentChildren
}

export function Card({ branding, children }: Props) {
  return (
    <div class="card bg-base-100 shadow-xl w-full max-w-md border border-base-200/50">
      <div class="card-body p-8">
        {branding.logoUrl && (
          <div class="text-center mb-4">
            <img src={branding.logoUrl} alt="Logo" class="max-w-36 max-h-15 mx-auto" />
          </div>
        )}
        {children}
      </div>
    </div>
  )
}
