// ui/src/admin/BrandingEditor.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { AdminPage, UserPool, UserPoolClient } from '../lib/types'
  import { listUserPoolClients, createManagedLoginBranding, updateManagedLoginBranding } from '../lib/api'

  interface Props {
    userPool: UserPool
    navigate: (page: AdminPage, context?: { userPool?: UserPool }) => void
  }

  let { userPool, navigate }: Props = $props()

  let clients: UserPoolClient[] = $state([])
  let selectedClientId = $state('')
  let brandingId: string | null = $state(null)
  let loading = $state(true)
  let saving = $state(false)
  let error: string | null = $state(null)
  let success: string | null = $state(null)

  // Branding settings
  let pageTitle = $state('Sign In')
  let signInHeader = $state('Welcome')
  let signInSubheader = $state('Sign in to continue')
  let backgroundColor = $state('#f5f5f5')
  let primaryColor = $state('#007bff')
  let textColor = $state('#333333')
  let buttonColor = $state('#007bff')
  let buttonTextColor = $state('#ffffff')

  async function loadClients() {
    try {
      loading = true
      clients = await listUserPoolClients(userPool.Id)
      if (clients.length > 0) {
        selectedClientId = clients[0].ClientId
      }
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load clients'
    } finally {
      loading = false
    }
  }

  async function handleSave() {
    if (!selectedClientId) {
      error = 'Please select a client'
      return
    }

    try {
      saving = true
      error = null

      const settings = {
        PageTitle: pageTitle,
        SignInHeader: signInHeader,
        SignInSubheader: signInSubheader,
        Colors: {
          BackgroundColor: backgroundColor,
          PrimaryColor: primaryColor,
          TextColor: textColor,
          ButtonColor: buttonColor,
          ButtonTextColor: buttonTextColor,
        },
      }

      if (brandingId) {
        await updateManagedLoginBranding(userPool.Id, brandingId, settings)
      } else {
        const branding = await createManagedLoginBranding(userPool.Id, selectedClientId, settings)
        brandingId = branding.ManagedLoginBrandingId
      }

      success = 'Branding saved successfully!'
      setTimeout(() => (success = null), 3000)
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to save branding'
    } finally {
      saving = false
    }
  }

  function getPreviewUrl(): string {
    if (!selectedClientId) return ''
    const client = clients.find(c => c.ClientId === selectedClientId)
    const callbackUrl = client?.CallbackURLs?.[0] || 'http://localhost:3000/callback'
    return `http://localhost:9229/ui/?response_type=code&client_id=${selectedClientId}&redirect_uri=${encodeURIComponent(callbackUrl)}&scope=openid`
  }

  onMount(loadClients)
</script>

<div class="page">
  <header class="page-header">
    <div class="breadcrumb">
      <button class="link-btn" onclick={() => navigate('user-pools')}>User Pools</button>
      <span>/</span>
      <button class="link-btn" onclick={() => navigate('user-pool-detail', { userPool })}>{userPool.Name}</button>
      <span>/</span>
      <span>Branding</span>
    </div>
    <h1>Hosted UI Branding</h1>
    <p>Customize the appearance of your login page</p>
  </header>

  {#if error}
    <div class="error-banner">
      {error}
      <button class="btn-close" onclick={() => (error = null)}>Dismiss</button>
    </div>
  {/if}

  {#if success}
    <div class="success-banner">{success}</div>
  {/if}

  {#if loading}
    <div class="loading">Loading...</div>
  {:else if clients.length === 0}
    <div class="empty-state">
      <h2>No App Clients</h2>
      <p>Create an app client first to configure branding.</p>
      <button class="btn btn-primary" onclick={() => navigate('clients', { userPool })}>
        Create Client
      </button>
    </div>
  {:else}
    <div class="editor-layout">
      <div class="editor-form">
        <section class="form-section">
          <h2>App Client</h2>
          <div class="form-group">
            <label for="client">Select Client</label>
            <select id="client" bind:value={selectedClientId}>
              {#each clients as client}
                <option value={client.ClientId}>{client.ClientName}</option>
              {/each}
            </select>
          </div>
        </section>

        <section class="form-section">
          <h2>Text Content</h2>
          <div class="form-group">
            <label for="pageTitle">Page Title</label>
            <input type="text" id="pageTitle" bind:value={pageTitle} />
          </div>
          <div class="form-group">
            <label for="signInHeader">Sign In Header</label>
            <input type="text" id="signInHeader" bind:value={signInHeader} />
          </div>
          <div class="form-group">
            <label for="signInSubheader">Sign In Subheader</label>
            <input type="text" id="signInSubheader" bind:value={signInSubheader} />
          </div>
        </section>

        <section class="form-section">
          <h2>Colors</h2>
          <div class="color-grid">
            <div class="form-group">
              <label for="backgroundColor">Background</label>
              <div class="color-input">
                <input type="color" id="backgroundColor" bind:value={backgroundColor} />
                <input type="text" bind:value={backgroundColor} />
              </div>
            </div>
            <div class="form-group">
              <label for="primaryColor">Primary</label>
              <div class="color-input">
                <input type="color" id="primaryColor" bind:value={primaryColor} />
                <input type="text" bind:value={primaryColor} />
              </div>
            </div>
            <div class="form-group">
              <label for="textColor">Text</label>
              <div class="color-input">
                <input type="color" id="textColor" bind:value={textColor} />
                <input type="text" bind:value={textColor} />
              </div>
            </div>
            <div class="form-group">
              <label for="buttonColor">Button</label>
              <div class="color-input">
                <input type="color" id="buttonColor" bind:value={buttonColor} />
                <input type="text" bind:value={buttonColor} />
              </div>
            </div>
            <div class="form-group">
              <label for="buttonTextColor">Button Text</label>
              <div class="color-input">
                <input type="color" id="buttonTextColor" bind:value={buttonTextColor} />
                <input type="text" bind:value={buttonTextColor} />
              </div>
            </div>
          </div>
        </section>

        <div class="form-actions">
          <button class="btn btn-primary" onclick={handleSave} disabled={saving}>
            {saving ? 'Saving...' : 'Save Branding'}
          </button>
          {#if selectedClientId}
            <a href={getPreviewUrl()} target="_blank" rel="noopener" class="btn btn-secondary">
              Preview
            </a>
          {/if}
        </div>
      </div>

      <div class="preview-panel">
        <h2>Preview</h2>
        <div class="preview-container" style="background-color: {backgroundColor}">
          <div class="preview-card">
            <h3 style="color: {textColor}">{signInHeader}</h3>
            <p style="color: {textColor}; opacity: 0.7">{signInSubheader}</p>
            <div class="preview-input">
              <span>Username</span>
            </div>
            <div class="preview-input">
              <span>Password</span>
            </div>
            <div
              class="preview-button"
              style="background-color: {buttonColor}; color: {buttonTextColor}"
            >
              Sign In
            </div>
            <div class="preview-link" style="color: {primaryColor}">
              Forgot password?
            </div>
          </div>
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .page {
    max-width: 1400px;
  }

  .page-header {
    margin-bottom: 32px;
  }

  .breadcrumb {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
    color: #666;
    margin-bottom: 16px;
  }

  .breadcrumb span {
    color: #999;
  }

  .page-header h1 {
    font-size: 28px;
    font-weight: 600;
    margin: 0 0 8px 0;
    color: #1a1a2e;
  }

  .page-header p {
    color: #666;
    margin: 0;
  }

  .error-banner {
    background-color: #fee;
    border: 1px solid #fcc;
    color: #c00;
    padding: 16px;
    border-radius: 8px;
    margin-bottom: 24px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .success-banner {
    background-color: #e8f5e9;
    border: 1px solid #c8e6c9;
    color: #2e7d32;
    padding: 16px;
    border-radius: 8px;
    margin-bottom: 24px;
  }

  .btn-close {
    background: none;
    border: none;
    color: #c00;
    cursor: pointer;
    font-size: 14px;
  }

  .loading {
    text-align: center;
    padding: 40px;
    color: #666;
  }

  .empty-state {
    background: white;
    padding: 60px;
    border-radius: 12px;
    text-align: center;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .empty-state h2 {
    font-size: 20px;
    margin: 0 0 8px 0;
    color: #1a1a2e;
  }

  .empty-state p {
    color: #666;
    margin: 0 0 24px 0;
  }

  .editor-layout {
    display: grid;
    grid-template-columns: 1fr 400px;
    gap: 32px;
  }

  @media (max-width: 1024px) {
    .editor-layout {
      grid-template-columns: 1fr;
    }
  }

  .editor-form {
    background: white;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .form-section {
    margin-bottom: 32px;
  }

  .form-section h2 {
    font-size: 16px;
    font-weight: 600;
    margin: 0 0 16px 0;
    color: #1a1a2e;
    padding-bottom: 8px;
    border-bottom: 1px solid #eee;
  }

  .form-group {
    margin-bottom: 16px;
  }

  .form-group label {
    display: block;
    margin-bottom: 6px;
    font-size: 14px;
    font-weight: 500;
    color: #333;
  }

  .form-group input[type="text"],
  .form-group select {
    width: 100%;
    padding: 10px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
  }

  .form-group input:focus,
  .form-group select:focus {
    outline: none;
    border-color: #4fc3f7;
  }

  .color-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 16px;
  }

  .color-input {
    display: flex;
    gap: 8px;
  }

  .color-input input[type="color"] {
    width: 40px;
    height: 40px;
    padding: 0;
    border: 1px solid #ddd;
    border-radius: 6px;
    cursor: pointer;
  }

  .color-input input[type="text"] {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
    font-family: monospace;
  }

  .form-actions {
    display: flex;
    gap: 12px;
    padding-top: 16px;
    border-top: 1px solid #eee;
  }

  .preview-panel {
    background: white;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    position: sticky;
    top: 24px;
    height: fit-content;
  }

  .preview-panel h2 {
    font-size: 16px;
    font-weight: 600;
    margin: 0 0 16px 0;
    color: #1a1a2e;
  }

  .preview-container {
    padding: 32px 16px;
    border-radius: 8px;
    min-height: 400px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .preview-card {
    background: white;
    padding: 32px;
    border-radius: 8px;
    width: 100%;
    max-width: 300px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  }

  .preview-card h3 {
    font-size: 20px;
    font-weight: 600;
    margin: 0 0 8px 0;
    text-align: center;
  }

  .preview-card p {
    font-size: 13px;
    margin: 0 0 24px 0;
    text-align: center;
  }

  .preview-input {
    background: #f5f5f5;
    padding: 12px;
    border-radius: 4px;
    margin-bottom: 12px;
    font-size: 13px;
    color: #999;
  }

  .preview-button {
    padding: 12px;
    border-radius: 4px;
    text-align: center;
    font-weight: 500;
    font-size: 14px;
    margin-bottom: 16px;
  }

  .preview-link {
    text-align: center;
    font-size: 13px;
  }

  .link-btn {
    background: none;
    border: none;
    color: #4fc3f7;
    cursor: pointer;
    font-size: inherit;
    font-weight: 500;
    padding: 0;
  }

  .link-btn:hover {
    text-decoration: underline;
  }

  .btn {
    padding: 12px 24px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
    text-decoration: none;
    display: inline-block;
    text-align: center;
  }

  .btn-primary {
    background-color: #4fc3f7;
    color: white;
  }

  .btn-primary:hover {
    background-color: #29b6f6;
  }

  .btn-secondary {
    background-color: #e0e0e0;
    color: #333;
  }

  .btn-secondary:hover {
    background-color: #d0d0d0;
  }

  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
</style>

// ui/src/admin/BrandingEditor.tsx
import { useState, useEffect } from 'preact/hooks'
import type { AdminPage, UserPool, UserPoolClient } from '../lib/types'
import { listUserPoolClients, createManagedLoginBranding, updateManagedLoginBranding } from '../lib/api'

interface Props {
  userPool: UserPool
  navigate: (page: AdminPage, context?: { userPool?: UserPool }) => void
}

export function BrandingEditor({ userPool, navigate }: Props) {
  const [clients, setClients] = useState<UserPoolClient[]>([])
  const [selectedClientId, setSelectedClientId] = useState('')
  const [brandingId, setBrandingId] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)

  const [pageTitle, setPageTitle] = useState('Sign In')
  const [signInHeader, setSignInHeader] = useState('Welcome')
  const [signInSubheader, setSignInSubheader] = useState('Sign in to continue')
  const [backgroundColor, setBackgroundColor] = useState('#f5f5f5')
  const [primaryColor, setPrimaryColor] = useState('#007bff')
  const [textColor, setTextColor] = useState('#333333')
  const [buttonColor, setButtonColor] = useState('#007bff')
  const [buttonTextColor, setButtonTextColor] = useState('#ffffff')

  useEffect(() => {
    listUserPoolClients(userPool.Id)
      .then(c => {
        setClients(c)
        if (c.length > 0) setSelectedClientId(c[0].ClientId)
      })
      .catch(e => setError(e instanceof Error ? e.message : 'Failed to load clients'))
      .finally(() => setLoading(false))
  }, [userPool.Id])

  async function handleSave() {
    if (!selectedClientId) { setError('Please select a client'); return }
    try {
      setSaving(true)
      setError(null)
      const settings = {
        PageTitle: pageTitle,
        SignInHeader: signInHeader,
        SignInSubheader: signInSubheader,
        Colors: { BackgroundColor: backgroundColor, PrimaryColor: primaryColor, TextColor: textColor, ButtonColor: buttonColor, ButtonTextColor: buttonTextColor },
      }
      if (brandingId) {
        await updateManagedLoginBranding(userPool.Id, brandingId, settings)
      } else {
        const branding = await createManagedLoginBranding(userPool.Id, selectedClientId, settings)
        setBrandingId(branding.ManagedLoginBrandingId)
      }
      setSuccess('Branding saved successfully!')
      setTimeout(() => setSuccess(null), 3000)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to save branding')
    } finally {
      setSaving(false)
    }
  }

  function getPreviewUrl(): string {
    if (!selectedClientId) return ''
    const client = clients.find(c => c.ClientId === selectedClientId)
    const callbackUrl = client?.CallbackURLs?.[0] || 'http://localhost:3000/callback'
    return `http://localhost:9229/ui/?response_type=code&client_id=${selectedClientId}&redirect_uri=${encodeURIComponent(callbackUrl)}&scope=openid`
  }

  const colorFields = [
    { label: 'Background', value: backgroundColor, setter: setBackgroundColor },
    { label: 'Primary', value: primaryColor, setter: setPrimaryColor },
    { label: 'Text', value: textColor, setter: setTextColor },
    { label: 'Button', value: buttonColor, setter: setButtonColor },
    { label: 'Button Text', value: buttonTextColor, setter: setButtonTextColor },
  ]

  return (
    <div class="max-w-7xl">
      <div class="mb-8">
        <div class="breadcrumbs text-sm mb-2">
          <ul>
            <li><button class="link link-primary" onClick={() => navigate('user-pools')}>User Pools</button></li>
            <li><button class="link link-primary" onClick={() => navigate('user-pool-detail', { userPool })}>{userPool.Name}</button></li>
            <li>Branding</li>
          </ul>
        </div>
        <h1 class="text-3xl font-bold">Hosted UI Branding</h1>
        <p class="text-base-content/60">Customize the appearance of your login page</p>
      </div>

      {error && (
        <div class="alert alert-error mb-6">
          <span>{error}</span>
          <button class="btn btn-ghost btn-sm" onClick={() => setError(null)}>Dismiss</button>
        </div>
      )}
      {success && <div class="alert alert-success mb-6">{success}</div>}

      {loading ? (
        <div class="flex justify-center p-10"><span class="loading loading-spinner loading-lg"></span></div>
      ) : clients.length === 0 ? (
        <div class="card bg-base-100 shadow">
          <div class="card-body items-center text-center py-16">
            <h2 class="card-title">No App Clients</h2>
            <p class="text-base-content/60">Create an app client first to configure branding.</p>
            <button class="btn btn-primary mt-4" onClick={() => navigate('clients', { userPool })}>Create Client</button>
          </div>
        </div>
      ) : (
        <div class="grid grid-cols-1 xl:grid-cols-[1fr_400px] gap-8">
          <div class="card bg-base-100 shadow">
            <div class="card-body">
              <h2 class="text-lg font-semibold border-b border-base-200 pb-2 mb-4">App Client</h2>
              <div class="form-control mb-6">
                <label class="label"><span class="label-text">Select Client</span></label>
                <select class="select select-bordered" value={selectedClientId} onChange={e => setSelectedClientId((e.target as HTMLSelectElement).value)}>
                  {clients.map(c => <option key={c.ClientId} value={c.ClientId}>{c.ClientName}</option>)}
                </select>
              </div>

              <h2 class="text-lg font-semibold border-b border-base-200 pb-2 mb-4">Text Content</h2>
              <div class="form-control mb-3">
                <label class="label"><span class="label-text">Page Title</span></label>
                <input type="text" class="input input-bordered" value={pageTitle} onInput={e => setPageTitle((e.target as HTMLInputElement).value)} />
              </div>
              <div class="form-control mb-3">
                <label class="label"><span class="label-text">Sign In Header</span></label>
                <input type="text" class="input input-bordered" value={signInHeader} onInput={e => setSignInHeader((e.target as HTMLInputElement).value)} />
              </div>
              <div class="form-control mb-6">
                <label class="label"><span class="label-text">Sign In Subheader</span></label>
                <input type="text" class="input input-bordered" value={signInSubheader} onInput={e => setSignInSubheader((e.target as HTMLInputElement).value)} />
              </div>

              <h2 class="text-lg font-semibold border-b border-base-200 pb-2 mb-4">Colors</h2>
              <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                {colorFields.map(({ label, value, setter }) => (
                  <div key={label} class="form-control">
                    <label class="label"><span class="label-text">{label}</span></label>
                    <div class="flex gap-2">
                      <input type="color" class="w-10 h-10 rounded cursor-pointer border border-base-300" value={value} onInput={e => setter((e.target as HTMLInputElement).value)} />
                      <input type="text" class="input input-bordered input-sm flex-1 font-mono" value={value} onInput={e => setter((e.target as HTMLInputElement).value)} />
                    </div>
                  </div>
                ))}
              </div>

              <div class="flex gap-3 pt-4 border-t border-base-200">
                <button class="btn btn-primary" onClick={handleSave} disabled={saving}>
                  {saving ? <><span class="loading loading-spinner loading-sm"></span> Saving...</> : 'Save Branding'}
                </button>
                {selectedClientId && (
                  <a href={getPreviewUrl()} target="_blank" rel="noopener" class="btn btn-outline">Preview</a>
                )}
              </div>
            </div>
          </div>

          <div class="card bg-base-100 shadow sticky top-6 h-fit">
            <div class="card-body">
              <h2 class="text-lg font-semibold mb-4">Preview</h2>
              <div class="rounded-lg p-8 min-h-96 flex items-center justify-center" style={{ backgroundColor }}>
                <div class="bg-white rounded-lg p-8 w-full max-w-xs shadow-lg">
                  <h3 class="text-xl font-semibold text-center mb-2" style={{ color: textColor }}>{signInHeader}</h3>
                  <p class="text-center text-sm mb-6" style={{ color: textColor, opacity: 0.7 }}>{signInSubheader}</p>
                  <div class="bg-gray-100 rounded p-3 mb-3 text-sm text-gray-400">Username</div>
                  <div class="bg-gray-100 rounded p-3 mb-3 text-sm text-gray-400">Password</div>
                  <div class="rounded p-3 text-center font-medium text-sm mb-4" style={{ backgroundColor: buttonColor, color: buttonTextColor }}>Sign In</div>
                  <div class="text-center text-sm" style={{ color: primaryColor }}>Forgot password?</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
