// ui/src/admin/Dashboard.tsx
import { useState, useEffect } from 'preact/hooks'
import type { AdminPage, UserPool } from '../lib/types'
import { listUserPools } from '../lib/api'

interface Props {
  navigate: (page: AdminPage, context?: { userPool?: UserPool }) => void
}

export function Dashboard({ navigate }: Props) {
  const [userPools, setUserPools] = useState<UserPool[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    listUserPools()
      .then(pools => setUserPools(pools))
      .catch(e => setError(e instanceof Error ? e.message : 'Failed to load data'))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div class="max-w-6xl">
      <div class="mb-8">
        <h1 class="text-3xl font-bold">Dashboard</h1>
        <p class="text-base-content/60">Overview of your Cognito emulator</p>
      </div>

      {loading ? (
        <div class="flex justify-center p-10"><span class="loading loading-spinner loading-lg"></span></div>
      ) : error ? (
        <div class="alert alert-error mb-6">{error}</div>
      ) : (
        <>
          <div class="stats shadow mb-8 w-full">
            <div class="stat">
              <div class="stat-title">User Pools</div>
              <div class="stat-value text-primary">{userPools.length}</div>
            </div>
            <div class="stat">
              <div class="stat-title">Total Users</div>
              <div class="stat-value text-primary">0</div>
            </div>
            <div class="stat">
              <div class="stat-title">App Clients</div>
              <div class="stat-value text-primary">0</div>
            </div>
          </div>

          <div class="card bg-base-100 shadow mb-6">
            <div class="card-body">
              <h2 class="card-title">User Pools</h2>
              {userPools.length === 0 ? (
                <div class="text-center py-8 text-base-content/60">
                  <p class="mb-4">No user pools yet.</p>
                  <button class="btn btn-primary" onClick={() => navigate('user-pools')}>Create User Pool</button>
                </div>
              ) : (
                <>
                  <div class="overflow-x-auto">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>ID</th>
                          <th>Created</th>
                          <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                        {userPools.slice(0, 5).map(pool => (
                          <tr key={pool.Id}>
                            <td>{pool.Name}</td>
                            <td><code class="badge badge-ghost text-xs">{pool.Id}</code></td>
                            <td>{new Date(pool.CreationDate).toLocaleDateString()}</td>
                            <td>
                              <button class="btn btn-ghost btn-sm" onClick={() => navigate('user-pool-detail', { userPool: pool })}>View</button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                  {userPools.length > 5 && (
                    <button class="btn btn-link" onClick={() => navigate('user-pools')}>View all {userPools.length} user pools</button>
                  )}
                </>
              )}
            </div>
          </div>

          <div class="card bg-base-100 shadow">
            <div class="card-body">
              <h2 class="card-title">Quick Actions</h2>
              <div class="flex gap-3 flex-wrap">
                <button class="btn btn-primary" onClick={() => navigate('user-pools')}>Manage User Pools</button>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  )
}

// ui/src/admin/Dashboard.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import type { AdminPage, UserPool } from '../lib/types'
  import { listUserPools } from '../lib/api'

  interface Props {
    navigate: (page: AdminPage, context?: { userPool?: UserPool }) => void
  }

  let { navigate }: Props = $props()

  let userPools: UserPool[] = $state([])
  let totalUsers = $state(0)
  let totalClients = $state(0)
  let loading = $state(true)
  let error: string | null = $state(null)

  onMount(async () => {
    try {
      userPools = await listUserPools()
      totalUsers = userPools.length * 0 // We'd need to aggregate, placeholder for now
      totalClients = userPools.length * 0
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to load data'
    } finally {
      loading = false
    }
  })
</script>

<div class="dashboard">
  <header class="page-header">
    <h1>Dashboard</h1>
    <p>Overview of your Cognito emulator</p>
  </header>

  {#if loading}
    <div class="loading">Loading...</div>
  {:else if error}
    <div class="error-banner">{error}</div>
  {:else}
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-value">{userPools.length}</div>
        <div class="stat-label">User Pools</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">{totalUsers}</div>
        <div class="stat-label">Total Users</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">{totalClients}</div>
        <div class="stat-label">App Clients</div>
      </div>
    </div>

    <section class="recent-section">
      <h2>User Pools</h2>
      {#if userPools.length === 0}
        <div class="empty-state">
          <p>No user pools yet.</p>
          <button class="btn btn-primary" onclick={() => navigate('user-pools')}>
            Create User Pool
          </button>
        </div>
      {:else}
        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>ID</th>
                <th>Created</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {#each userPools.slice(0, 5) as pool}
                <tr>
                  <td>{pool.Name}</td>
                  <td><code>{pool.Id}</code></td>
                  <td>{new Date(pool.CreationDate).toLocaleDateString()}</td>
                  <td>
                    <button
                      class="btn btn-sm"
                      onclick={() => navigate('user-pool-detail', { userPool: pool })}
                    >
                      View
                    </button>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
        {#if userPools.length > 5}
          <button class="btn btn-link" onclick={() => navigate('user-pools')}>
            View all {userPools.length} user pools
          </button>
        {/if}
      {/if}
    </section>

    <section class="quick-actions">
      <h2>Quick Actions</h2>
      <div class="action-buttons">
        <button class="btn btn-primary" onclick={() => navigate('user-pools')}>
          Manage User Pools
        </button>
      </div>
    </section>
  {/if}
</div>

<style>
  .dashboard {
    max-width: 1200px;
  }

  .page-header {
    margin-bottom: 32px;
  }

  .page-header h1 {
    font-size: 28px;
    font-weight: 600;
    margin: 0 0 8px 0;
    color: #1a1a2e;
  }

  .page-header p {
    color: #666;
    margin: 0;
  }

  .loading {
    text-align: center;
    padding: 40px;
    color: #666;
  }

  .error-banner {
    background-color: #fee;
    border: 1px solid #fcc;
    color: #c00;
    padding: 16px;
    border-radius: 8px;
    margin-bottom: 24px;
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 24px;
    margin-bottom: 40px;
  }

  .stat-card {
    background: white;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .stat-value {
    font-size: 36px;
    font-weight: 700;
    color: #4fc3f7;
  }

  .stat-label {
    font-size: 14px;
    color: #666;
    margin-top: 4px;
  }

  .recent-section {
    background: white;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    margin-bottom: 24px;
  }

  .recent-section h2 {
    font-size: 18px;
    font-weight: 600;
    margin: 0 0 16px 0;
    color: #1a1a2e;
  }

  .table-container {
    overflow-x: auto;
  }

  table {
    width: 100%;
    border-collapse: collapse;
  }

  th, td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #eee;
  }

  th {
    font-weight: 600;
    color: #666;
    font-size: 13px;
    text-transform: uppercase;
  }

  td code {
    background: #f5f5f5;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 12px;
  }

  .empty-state {
    text-align: center;
    padding: 40px;
    color: #666;
  }

  .quick-actions {
    background: white;
    padding: 24px;
    border-radius: 12px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  }

  .quick-actions h2 {
    font-size: 18px;
    font-weight: 600;
    margin: 0 0 16px 0;
    color: #1a1a2e;
  }

  .action-buttons {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
  }

  .btn {
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn-primary {
    background-color: #4fc3f7;
    color: white;
  }

  .btn-primary:hover {
    background-color: #29b6f6;
  }

  .btn-sm {
    padding: 6px 12px;
    font-size: 13px;
    background-color: #f0f0f0;
    color: #333;
  }

  .btn-sm:hover {
    background-color: #e0e0e0;
  }

  .btn-link {
    background: none;
    color: #4fc3f7;
    padding: 8px 0;
    margin-top: 12px;
  }

  .btn-link:hover {
    text-decoration: underline;
  }
</style>
